/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tech_liangfang_springbootdemopractice_jni_HelloWord */

#ifndef _Included_tech_liangfang_springbootdemopractice_jni_HelloWord
#define _Included_tech_liangfang_springbootdemopractice_jni_HelloWord
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tech_liangfang_springbootdemopractice_jni_HelloWord
 * Method:    sayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tech_liangfang_springbootdemopractice_jni_HelloWord_sayHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
